from typing import Final

DEFAULT_USAGE_STREAM_MAX_LENGTH: Final[int] = 250_000
MAX_USAGE_STREAM_LENGTH: Final[int] = 250_000
DEFAULT_USAGE_RETENTION_MONTHS: Final[int] = 3
MAX_USAGE_RETENTION_MONTHS: Final[int] = 3
DEFAULT_USAGE_FINE_RETENTION_HOURS: Final[int] = 48
MAX_USAGE_FINE_RETENTION_HOURS: Final[int] = 168
